[package]
name = "reel-api"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with.workspace = true
axum = { workspace = true }
reqwest = { workspace = true, features = ["json", "query", "stream"] }
rand.workspace = true
url.workspace = true
percent-encoding.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tower-http = { workspace = true, features = ["trace"] }
base64.workspace = true
dotenvy.workspace = true
thiserror.workspace = true

[dev-dependencies]
dotenvy.workspace = true
tower = { version = "0.5", features = ["util"] }
